spec_version = 1
id = "KittenEngineerRedux"
type = "mod"
name = "Kitten Engineer Redux"
authors = ["BarneyTheGod"]
abstract = "Utility mod for KSA that mirrors KSP's Kerbal Engineer Redux."
description = """
Kitten Engineer Redux is a utility readout mod for Kitten Space Agency. It aims to mirror the KSP mod "Kerbal Engineer Redux" by providing the player with useful vehicle data inside of the VAB and during flight.

Dependencies:
 - [ModMenu](https://github.com/MrJeranimo/ModMenu/)"""
license = "MIT"
tags = ["gameplay", "user-interface"]

[releases]
github = "BarneyCompiler/Kitten-Engineer-Redux"
spacedock = 4043
authority = "github"

[links]
forums = "https://forums.ahwoo.com/forums/kitten-space-agency/mod-releases/kitten-engineer-redux-ker.443/"
homepage = "https://github.com/BarneyCompiler/Kitten-Engineer-Redux"
repository = "https://github.com/BarneyCompiler/Kitten-Engineer-Redux"
spacedock = "https://spacedock.info/mod/4043/Kitten%20Engineer%20Redux"
bugtracker = "https://github.com/BarneyCompiler/Kitten-Engineer-Redux/issues"

[compatibility]
game_min = "2026.10.7.5541"
game_max = "2026.10.7.5541"

[loader]
id = "StarMap"
min = "0.4.7"
max = "0.4.7"

[[dependencies]]
id = "ModMenu"
kind = "required"
min = "0.2.2"
max = "0.2.2"

[images.icon]
url = "https://i.imgur.com/YQXQrtm.png"
sha256 = "3c528ca59bbb0462858f7d39dd0553ba5490a485fec14e1f682e15570a37eebc"
width = 512
height = 512
size = 183766
license = "MIT"
attribution = "BarneyTheGod"
